name: Ruby

on: [push,pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.0
    - name: Run the default task
      run: |
        gem install bundler -v 2.3.3
        bundle install
        bundle exec rake rubocop
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.0
    - name: Run the default task
      run: |
        gem install bundler -v 2.3.3
        bundle install
        bundle exec rake test
  gh-pages:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/docs
        key: ${{ runner.os }}-rdoc-${{ hashFiles('docs/created.rid') }}
        restore-keys: |
          ${{ runner.os }}-rdoc-
    - name: Build RDoc
      run: |
        gem install bundler -v 2.3.3
        bundle install
        bundle exec rake rerdoc
    - name: Deploy Documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        cname: refinement.monkey-patch.me
